[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D ASYNC_JSON_SUPPORT=1
	-I.pio/libdeps/esp32dev/ArduinoJson/src
	-O2
test_framework = unity
lib_ldf_mode = deep+
test_build_src = true
lib_deps = 
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display @ ^3.0.11
	bitbank2/AnimatedGIF @ ^2.1.1
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
	bblanchon/ArduinoJson @ ^6.21.5
	knolleary/PubSubClient @ ^2.8
	adafruit/Adafruit GFX Library @ ^1.11.9


