import os
import sys
import subprocess
import time
import re

import gzip
import hashlib

input_file = "data/index.html"
output_file = "src/api/WebUI.h"

if not os.path.exists(input_file):
    print(f"Error: {input_file} not found.")
    sys.exit(1)

# Validate inline JavaScript and Hardware Isolation in data/index.html before bundling
try:
    with open(input_file, "r", encoding="utf-8") as f:
        html_text = f.read()

    # Hardware Isolation Verification (GEMINI.md Invariant 8.4)
    FORBIDDEN_RPI_TERMS = [
        'id="hw-slowdown"',
        'id="hw-mapping"',
        'id="hw-disable-pulsing"',
        'id="hw-pwm-lsb"',
        'id="hw-multiplexing"',
        'Slowdown for fast Pi',
        'Raspberry Pi 40-Pin GPIO Options',
    ]
    for term in FORBIDDEN_RPI_TERMS:
        if term in html_text:
            print(f"❌ FATAL ERROR: Raspberry Pi hardware setting '{term}' detected in {input_file}!")
            print("ESP32 WebUI must NEVER contain Raspberry Pi hardware settings.")
            print("See GEMINI.md Section 8. Aborting build.")
            sys.exit(1)

    REQUIRED_ESP32_TERMS = [
        "hw-caps-grid",
        "hw-screen-rotation",
        "hw-gyro-autorotate",
        "btn-gyro-calibrate",
        "hw-driver-chip",
        "hw-color-depth",
        "hw-row-addr-type",
        "hw-latch-blanking",
        "hw-clk-phase",
        "hw-force-single-buffer",
    ]
    for term in REQUIRED_ESP32_TERMS:
        if term not in html_text:
            print(f"❌ FATAL ERROR: Required ESP32 hardware setting '{term}' missing from {input_file}!")
            print("See GEMINI.md Section 8. Aborting build.")
            sys.exit(1)

    parts = html_text.split("<script>")
    for idx, part in enumerate(parts[1:], 1):
        script_code = part.split("</script>")[0]
        res = subprocess.run(["node", "--check", "-"], input=script_code, text=True, capture_output=True)
        if res.returncode != 0:
            print(f"❌ JavaScript SyntaxError detected in {input_file} (script block {idx}):")
            print(res.stderr)
            sys.exit(1)
    print("✅ All JavaScript script blocks and Hardware Isolation in data/index.html passed validation.")
except FileNotFoundError:
    pass # node not found in environment

def minify_webui(content):
    # Strip HTML comments (preserves potential conditional comments)
    content = re.sub(r'<!--(?!\s*#(?:[if|endif|else|elif]))[\s\S]*?-->', '', content)
    # Minify CSS inside style tags
    def replace_style(match):
        attrs = match.group(1)
        css = match.group(2)
        css = re.sub(r'/\*[\s\S]*?\*/', '', css)
        css = re.sub(r'\s+', ' ', css)
        css = re.sub(r'\s*([\{\};:,>+~])\s*', r'\1', css)
        return f'<style{attrs}>{css.strip()}</style>'
    content = re.sub(r'<style([^>]*)>([\s\S]*?)</style>', replace_style, content)
    return content

minified_html = minify_webui(html_text)
raw_data = minified_html.encode('utf-8')

# Gzip compress WebUI HTML to save ~190KB flash and prevent LwIP TCP buffer exhaustion
data = gzip.compress(raw_data, compresslevel=9)

# Content-based ETag: derived from the *payload*, not from the git commit. A commit-derived tag
# never changes when data/index.html is edited without committing, so browsers kept serving a
# stale cached UI during development.
etag = hashlib.sha256(raw_data).hexdigest()[:16]

out = []
out.append(f"// Auto-generated by scripts/build_webui.py")
out.append(f"// Compressed Size: {len(data)} bytes (minified uncompressed: {len(raw_data)} bytes)")
out.append(f"const size_t WebUI_html_len = {len(data)};")
out.append(f'const char WebUI_html_etag[] = "{etag}";')
out.append("const uint8_t WebUI_html[] PROGMEM = {")

# Format bytes into hex array (12 bytes per line)
bytes_strs = [f"0x{b:02x}" for b in data]
for i in range(0, len(bytes_strs), 12):
    out.append("  " + ", ".join(bytes_strs[i:i+12]) + ",")

out.append("};")

with open(output_file, "w") as f:
    f.write("\n".join(out))
    f.write("\n")

print(f"Successfully generated {output_file} ({len(data)} bytes gzipped, saved {len(raw_data) - len(data)} bytes).")

# Determine Firmware Version dynamically from CI/CD Tag -> Git Tag -> VERSION file
firmware_version = ""

# 1. Check CI/CD environment variable (e.g. GITHUB_REF_NAME when pushed with tag v3.0.1)
ref_name = os.environ.get("GITHUB_REF_NAME", "")
if ref_name.startswith("v") and re.match(r"^v\d+\.\d+", ref_name):
    firmware_version = ref_name.lstrip("v")

# 2. Dynamic Git Tag detection via git describe
if not firmware_version:
    try:
        tag_desc = subprocess.check_output(['git', 'describe', '--tags', '--always']).decode('ascii').strip()
        m = re.match(r"^v?(\d+\.\d+\.\d+)", tag_desc)
        if m:
            firmware_version = m.group(1)
            if "-" in tag_desc and not tag_desc.startswith(f"v{firmware_version}-0"):
                firmware_version = f"{firmware_version}-dev"
        elif tag_desc:
            firmware_version = tag_desc.lstrip("v")
    except Exception:
        pass

# 3. Read base version from VERSION file if present
if not firmware_version:
    version_file = "VERSION"
    if os.path.exists(version_file):
        with open(version_file, "r") as vf:
            firmware_version = vf.read().strip().lstrip("v")

# 4. Fallback if still empty
if not firmware_version:
    firmware_version = "0.0.0"

# Generate Git commit hash
try:
    git_commit = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).decode('ascii').strip()
except Exception:
    git_commit = "unknown"

build_timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
with open("src/core/BuildInfo.h", "w") as f:
    f.write(f'#pragma once\n'
            f'#ifndef FIRMWARE_VERSION\n#define FIRMWARE_VERSION "{firmware_version}"\n#endif\n'
            f'#ifndef BUILD_GIT_COMMIT\n#define BUILD_GIT_COMMIT "{git_commit}"\n#endif\n'
            f'#ifndef BUILD_TIMESTAMP\n#define BUILD_TIMESTAMP "{build_timestamp}"\n#endif\n')
print(f"Successfully generated src/core/BuildInfo.h (v{firmware_version}, commit {git_commit}).")

try:
    Import("env")
    env.Append(CPPDEFINES=[("BUILD_GIT_COMMIT", f'\\"{git_commit}\\"')])
except Exception:
    pass

