import os
import sys

input_file = "scrap/data_src/dist/index.html"
output_file = "src/WebUI.h"

if not os.path.exists(input_file):
    print(f"Error: {input_file} not found. Please run 'npm run build' first.")
    sys.exit(1)

with open(input_file, "rb") as f:
    data = f.read()

out = []
out.append(f"// Auto-generated by scripts/build_webui.py")
out.append(f"// Size: {len(data)} bytes")
out.append(f"const size_t WebUI_html_len = {len(data)};")
out.append("const uint8_t WebUI_html[] PROGMEM = {")

# Format bytes into hex array (12 bytes per line)
bytes_strs = [f"0x{b:02x}" for b in data]
for i in range(0, len(bytes_strs), 12):
    out.append("  " + ", ".join(bytes_strs[i:i+12]) + ",")

out.append("};")

with open(output_file, "w") as f:
    f.write("\n".join(out))
    f.write("\n")

print(f"Successfully generated {output_file} ({len(data)} bytes).")
